"""Generate docs/API_INDEX.md: a module -> public-API map of the ``one``
package, so an assistant (or a human) can discover in-house functions
instead of reaching for trimesh / scipy / open3d.

Harvested statically with ``ast`` (no imports), so it is safe and fast and
never triggers hardware/GUI side effects. Re-run after adding functions:

    py -3.12 tools/gen_api_index.py
"""
import ast
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PKG = os.path.join(ROOT, 'one')
OUT = os.path.join(ROOT, 'docs', 'API_INDEX.md')


def _first_doc_line(node):
    doc = ast.get_docstring(node)
    if not doc:
        return ''
    return doc.strip().splitlines()[0].strip()


def _public_methods(cls):
    out = []
    for n in cls.body:
        if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef)):
            if not n.name.startswith('_') and n.name not in out:
                out.append(n.name)  # dedup property getter/setter pairs
    return out


def _module_entries(path):
    with open(path, 'r', encoding='utf-8') as f:
        src = f.read()
    try:
        tree = ast.parse(src)
    except SyntaxError:
        return None, []
    mod_doc = _first_doc_line(tree)
    funcs, classes = [], []
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            if node.name.startswith('_'):
                continue
            funcs.append((f'{node.name}({ast.unparse(node.args)})',
                          _first_doc_line(node)))
        elif isinstance(node, ast.ClassDef):
            if node.name.startswith('_'):
                continue
            classes.append((node.name, _first_doc_line(node),
                            _public_methods(node)))
    return mod_doc, funcs, classes


def main():
    rows = []
    for dirpath, dirnames, filenames in os.walk(PKG):
        if '__pycache__' in dirpath:
            continue
        dirnames.sort()
        for fn in sorted(filenames):
            if not fn.endswith('.py') or fn == '__init__.py':
                continue
            path = os.path.join(dirpath, fn)
            rel = os.path.relpath(path, ROOT).replace(os.sep, '/')
            mod = rel[:-3].replace('/', '.')
            mod_doc, funcs, classes = _module_entries(path)
            if not funcs and not classes:
                continue
            rows.append((mod, rel, mod_doc, funcs, classes))

    lines = ['# `one` API index',
             '',
             ('Auto-generated by `tools/gen_api_index.py` (static ast scan). '
              'Lists public functions/classes per module so in-house utilities '
              'are discoverable. Prefer these over trimesh / scipy / open3d / '
              'fcl. Re-run after adding functions.'),
             '']
    for mod, rel, mod_doc, funcs, classes in rows:
        lines.append(f'## `{mod}`')
        if mod_doc:
            lines.append(f'_{mod_doc}_')
        lines.append('')
        for name, doc in funcs:
            lines.append(f'- `{name}`' + (f' — {doc}' if doc else ''))
        for cname, cdoc, methods in classes:
            head = f'- **class `{cname}`**' + (f' — {cdoc}' if cdoc else '')
            lines.append(head)
            if methods:
                lines.append('  - methods: ' +
                             ', '.join(f'`{m}`' for m in methods))
        lines.append('')

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))
    n_funcs = sum(len(r[3]) for r in rows)
    n_classes = sum(len(r[4]) for r in rows)
    print(f'wrote {OUT}')
    print(f'{len(rows)} modules, {n_funcs} functions, {n_classes} classes')


if __name__ == '__main__':
    main()
